name = "testid1"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[[routes]]
pattern = "itrnet-host.my.id"
custom_domain = true

[vars]
PROXYIP = "35.219.50.99:443"
UUID = "dcbc851d-a89e-41b0-bfdf-56710ae09230"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
